AWSTemplateFormatVersion: '2010-09-09'
################################################################################
#
#DESCRIPTION
#
##############################################################################
################################################################################
#
#RESOURCES
#
##############################################################################
Resources:
  rECRRepo:
      Type: AWS::ECR::Repository
      Properties:
      RepositoryName: hello-server
      
  rECRRepoParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ECR Repository
      Name: ecr-repo-name
      Type: String
      Value: !Ref rECRRepo

  rECSLogGroup:
    Type: AWS::LogGroup
    Properties:
      LogGroupName: /ecs/hello-server

  rTaskDefinition:
    Type: AWS::ECS::TaskDefinition
  Properties:
    ContainerDefinitions:
    - Name: hello-server
    Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hello-server
    PortMappings:
    - ContainerPort: 80
    HostPort: 80
    Protocol: tcp
    Essential: true
    LogConfiguration:
    LogDriver: awslogs
  Options:
    awslogs-group: /ecs/hello-server
    awslogs-region: eu-west-1
    awslogs-stream-prefix: ecs
    Family: hello-server
    NetworkMode: bridge
    Memory: 256
    RequiresCompatibilities:
    - EC2
